name: Docker - Build and Freeze Matter Environment
# Este workflow clona el código fuente y empaqueta un búnker Docker personalizado

on:
  workflow_dispatch: # Lanzamiento manual desde la interfaz web

jobs:
  bake-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso obligatorio para poder subir la imagen a tu perfil de GitHub

    steps:
      - name: Checkout Local Repository (PubIrZ/MatterTVApp)
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # =========================================================================
      # CONSTRUCCIÓN DINÁMICA DEL BÚNKER: Inyectamos el SDK v1.3 dentro de Docker
      # =========================================================================
      - name: Build and Push Custom Matter Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          # Expresión corregida en minúsculas dinámicas y libre de errores sintácticos
          tags: ghcr.io/${{ lower(github.actor) }}/matter-frozen-env:latest

