name: Docker - Build and Freeze Matter Environment

on:
  workflow_dispatch: # Lanzamiento manual desde la interfaz web

jobs:
  bake-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso obligatorio para poder subir la imagen a tu perfil de GitHub
    
    steps:
      - name: Checkout Local Repository (PubIrZ/MatterTVApp)
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Pistas: Convertimos el actor a minúsculas usando Bash y lo guardamos en GITHUB_ENV
      - name: Set actor to lowercase
        run: |
          echo "ACTOR_LOWERCASE=${{ github.actor }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      # =========================================================================
      # CONSTRUCCIÓN DINÁMICA DEL BÚNKER: Inyectamos el SDK v1.3 dentro de Docker
      # =========================================================================
      - name: Build and Push Custom Matter Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          # Usamos la variable de entorno generada en el paso anterior
          tags: ghcr.io/${{ env.ACTOR_LOWERCASE }}/matter-frozen-env:latest
