name: Docker - Build and Freeze Matter Environment

on:
  workflow_dispatch: # Lanzamiento manual desde la interfaz web

jobs:
  bake-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso obligatorio para poder subir la imagen a tu perfil de GitHub
    
    steps:
      - name: Checkout Local Repository (PubIrZ/MatterTVApp)
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Este paso oficial genera los tags y formatea automáticamente todo a minúsculas
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/matter-frozen-env
          tags: |
            type=raw,value=latest

      # =========================================================================
      # CONSTRUCCIÓN DINÁMICA DEL BÚNKER: Inyectamos el SDK v1.3 dentro de Docker
      # =========================================================================
      - name: Build and Push Custom Matter Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          # Usamos la salida del paso anterior que ya viene sanitizada y en minúsculas
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
